import Card from "../../components/ui/Card";
import DataTable from "../../components/ui/DataTable";
import { ErrorState, LoadingState, Page, PageHeader } from "../../components/ui/Page";
import StatCard from "../../components/ui/StatCard";
import StatusBadge from "../../components/ui/StatusBadge";
import { useCurrentUser } from "../../hooks/useCurrentUser";
import { useDriverEarnings } from "../../hooks/useShipments";
import type { DriverEarning } from "../../types";

export default function Earnings() {
  const { driver } = useCurrentUser();
  const earnings = useDriverEarnings(driver?.id);
  const data = earnings.data ?? [];
  const total = data.reduce((sum, earning) => sum + Number(earning.amount ?? 0), 0);

  return (
    <Page>
      <PageHeader title="Earnings" description="Driver earning calculations generated by ShipmentService." />

      <div className="grid gap-4 md:grid-cols-3">
        <StatCard title="This Week" value={`₹${total.toLocaleString()}`} tone="green" icon="$" />
        <StatCard title="This Month" value={`₹${total.toLocaleString()}`} tone="blue" icon="↗" />
        <StatCard title="Total Deliveries" value={data.length} tone="purple" icon="✓" />
      </div>

      <Card>
        {earnings.isLoading ? (
          <LoadingState />
        ) : earnings.isError ? (
          <ErrorState message={earnings.error.message} />
        ) : (
          <DataTable<DriverEarning>
            data={data}
            keyExtractor={(row) => row.id}
            columns={[
              { header: "Shipment", accessor: "shipmentId" },
              { header: "Amount", accessor: (row) => <span className="font-bold">₹{row.amount}</span> },
              { header: "Status", accessor: (row) => <StatusBadge status={row.status} /> },
              { header: "Date", accessor: (row) => (row.createdAt ? new Date(row.createdAt).toLocaleDateString() : "—") },
            ]}
          />
        )}
      </Card>
    </Page>
  );
}
